package com.example.demo;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.example.demo.Highscore;
import com.example.demo.HighscoreRepository;

@RestController
@RequestMapping(path="/hangman") // This means URL's start with /hangman (after Application path)
public class MainController {
	@Autowired // This means to get the bean called highscoreRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private HighscoreRepository highscoreRepository;
	
	@PostMapping(path="/add") // Map ONLY Post Requests
	public String addNewUser (@RequestParam String name, @RequestParam Integer score) {
		// @RequestParam means it is a parameter from the GET or POST request
		
		Highscore hs = new Highscore();
		hs.setName(name);
		hs.setScore(score);
		highscoreRepository.save(hs);
		return "Saved\n";
	}
	
	@GetMapping(path="/topTen")
	public List<Highscore> getAllUsers() {
		// This returns a JSON or XML with the users
		List<Highscore> sortedList = (List<Highscore>) highscoreRepository.findAll();
		sortedList.sort((Highscore h1, Highscore h2) -> h1.getScore()-h2.getScore());
		return sortedList.subList(0, 10);
	}
}
